apiVersion: v1 # This just needs v1 since it is a service
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: rest-api # This should match the labels in the deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Port my application is listening to
  type: LoadBalancer # This uses the cloud provider or minikube to create a load balancer
