services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Configuration especified in the image documentation | ro - Read only
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # Delegated means that the container will have the same files as the host machine and it's better for performance
      # We're not adding ports here because nginx will be the one that will handle the requests not our local machine, so we'll need the port specified in the nginx configuration
  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env
  composer: # To create a laravel project run the command: docker-compose run --rm composer create-project --prefer-dist laravel/laravel .
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  #artisan:
  #npm:
